version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: user_center_backend
    restart: always
    environment:
      - SERVER_PORT=8080
      - DB_HOST=43.138.1.141
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Zhixin123..
      - DB_NAME=user_center
    ports:
      - "8080:8080"

  frontend:
    image: nginx:alpine
    container_name: user_center_frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
